### ISSUE TITLE
Error installing `pywry` when building `OpenBB Terminal` from source

### ISSUE THREAD

**Issue by jsr-p** [OpenBB-finance/pywry#46]
Hi 

I was trying to build  `OpenBB Terminal` from source but when running `poetry install -E all` your package failed to build.
I am using a computer with Ubuntu 22.04.

The error output I got was [this](https://gist.github.com/jsr-p/7f96cad691a4d72a631c1a1679e2bd65).

After running 
```bash
sudo apt-get install libjavascriptcoregtk-4.1-dev
```

I got an equivalent error, now saying that I need the package `libsoup-3.0`.

By running 
```bash
sudo apt install libsoup-3.0-dev
```

I again got an equivalent error, now saying that I need the package `libwebkit2gtk-4.1` :cowboy_hat_face: 

Finally, by running 
```bash
sudo apt install libwebkit2gtk-4.1-dev
```

and then `poetry install -E all` I succeeded in building `OpenBBTerminal`.

I am curious to why the dependency issues weren't handled by the underlying `Rust` code? 

Cheers
jsr-p

**Comment by andrewkenreich** [comment]
Hey jsr-p

As this is still the Dev branch we havent fully updated our docs to say what needs to be done on the installs.

![image](https://user-images.githubusercontent.com/23067478/224118297-62fc1872-8943-4015-a479-f0b3806e81ab.png)


Each flavor of Linux requires you to install a bit different package so its hard for us to say with certainty what needs to be installed - which is why we went with the build this way - On our docs we will definitely call out what needs to be done when installing on Linux and reference these packages.

**Comment by jsr-p** [comment]
Ah yes, of course.
Maybe a short hint to the dependencies inside [wry](https://github.com/tauri-apps/wry) would help the users building `OpenBB Terminal` directly without coming to this repo. 

Thanks :smiley:

**Comment by andrewkenreich** [comment]
ya we will add something :) ty
